
server:
  port: 8786
  max-http-header-size: 20480
spring:
  application:
    name: easyui-service
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nxtsnjzy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 最小连接池数量
    minIdle: 1
    # 最大连接池数量
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.entity

logging:
  level:
    com:
      example:
        mapper : debug
